### Лабораторная 1

#### 1.1

In [1]:
from scipy import integrate, stats

# функция распределения
function = lambda x: pow(x, 3) * (5 - x)
interval = (0, 5)

# интегрируем без параметра А
result = integrate.quad(function, interval[0], interval[1])
# получаем значение интеграла без A
value = round(result[0], 2)

# вычисляем значение A
A = 1 / value
A

0.0064

In [2]:
# проверяем, что нашли верное значение
full_function = lambda x: A * pow(x, 3) * (5 - x)
result = integrate.quad(full_function, interval[0], interval[1])
result[0]

1.0

In [3]:
import random
random.seed(123)

# генерируем u1 и u2
koef = 1000
N = 100

fix = lambda x: x / koef

def generate_u():
    u1 = random.uniform(0, 1)
    u2 = random.uniform(0, 1)

    return u1, u2

generate_u()

(0.052363598850944326, 0.08718667752263232)

In [4]:
# производная f(x)
diff_func = lambda x: pow(x, 2) * (15*A - 4*A*x)
# считаем точки экстремума
extremum_1 = 0
extremum_2 = 15 * A / 4 / A

extremum_1, extremum_2

(0, 3.75)

In [5]:
# считаем значения в точке экстремума
M = full_function(extremum_2)
M

0.421875

In [6]:
x1_func = lambda u1: interval[0] + (interval[1] - interval[0]) * u1
x2_func = lambda u2: M * u2

sample = []
while len(sample) < 100:
    u1, u2 = generate_u()
    is_correct = True
    
    x1 = x1_func(u1)
    x2 = x2_func(u2)

    f_x1 = full_function(x1)

    comparsion = x2 <= f_x1

    if comparsion:
        sample.append(x1)

sample.sort()
delta = (sample[-1] - sample[0]) / 5
sample[0], sample[-1]

(0.8167784805331141, 4.796128734360764)

In [19]:
intervals = [
    [sample[0] - 0.01, sample[0] + delta]
]

for i in range(4):
    intervals.append([intervals[-1][1], intervals[-1][1] + delta])

intervals[-1][-1] += 0.01
intervals

[[0.8067784805331141, 1.612648531298644],
 [1.612648531298644, 2.408518582064174],
 [2.408518582064174, 3.204388632829704],
 [3.204388632829704, 4.000258683595234],
 [4.000258683595234, 4.806128734360764]]

In [20]:
counts = [0, 0, 0, 0, 0]

for item in sample:
    for i in range(len(intervals)):
        if intervals[i][0] < item <= intervals[i][1]:
            counts[i] += 1
            break

counts = list(map(lambda x: x / 100, counts))
counts, sum(counts)

([0.06, 0.12, 0.23, 0.33, 0.26], 1.0)

In [9]:
p = [integrate.quad(full_function, interval[0], interval[1])[0] for interval in intervals]
p

[0.037193911374703556,
 0.12532029235824682,
 0.24555613144675426,
 0.3263638435276011,
 0.24871196240371904]

In [21]:
t_eval = sum([(counts[i] - p[i]) * (counts[i] - p[i]) / p[i] for i in range(5)])
t_eval

0.015748133275671858

In [11]:
t_crit = 0.71

#1.1.2

In [22]:
import numpy as np
from scipy.stats import norm

n = 5

avg_vect_elems = [int(item) for item in input("Введите вектор средних: ").split()][:n]
avg_vect = np.array(avg_vect_elems)
      
print(avg_vect)

[62 12 41 81 29]


In [13]:
cov_matrix = np.array(
 [[1, -1,  1, -1,  1],
 [-1,  2, -2,  2, -2,],
 [ 1, -2,  3, -3,  3],
 [-1,  2, -3, 4,  -4],
 [ 1, -2,  3, -4,  5]]
)

In [23]:
selection_data = []
for i in range(0, 200):
  observ = np.matmul(np.linalg.cholesky(cov_matrix), np.random.normal(0, 1, n).T)
  observ = np.add(observ, avg_vect)
  selection_data.append(observ)

selection = np.array(selection_data)
print("Выборка:\n", selection[:3])

Выборка:
 [[62.33999862 11.51488635 41.53804599 82.06017537 27.30288711]
 [61.86442263 12.53569194 39.92675213 85.13412945 22.89047058]
 [59.5781863  13.75142763 40.40142295 80.33663794 29.70246256]]


In [15]:
eval_cov_matrix = np.cov(selection.T)
print("Оценка матрицы ковариаций:\n", eval_cov_matrix)

Оценка матрицы ковариаций:
 [[ 0.99090533 -0.88231202  0.86590957 -0.8458856   0.82193846]
 [-0.88231202  1.68273987 -1.66699851  1.59734659 -1.56052406]
 [ 0.86590957 -1.66699851  2.59859571 -2.55192345  2.47814932]
 [-0.8458856   1.59734659 -2.55192345  3.50019369 -3.41972268]
 [ 0.82193846 -1.56052406  2.47814932 -3.41972268  4.22648396]]


In [16]:
[x, y] = list(map(int, input().split()))
x -= 1
y -= 1

print(f"Коэффициент корреляции между {x} и {y}:")
r_xy = np.corrcoef(selection.T[x], selection.T[y])[0, 1]
print(r_xy)

Коэффициент корреляции между 0 и 4:
0.40163690311690625


In [17]:
print("Коэффциент корреляции на основе матрицы ковариаций:")
r_0 = cov_matrix[x,y]/np.sqrt(cov_matrix[x,x]*cov_matrix[y,y])
print(r_0)

Коэффциент корреляции на основе матрицы ковариаций:
0.4472135954999579


In [18]:
z_xy = 0.5*np.log((1+r_xy)/(1-r_xy))
z_0 = 0.5*np.log((1+r_0)/(1-r_0))

alpha = 0.05

t_eval = np.sqrt(200-3)*np.abs(z_xy - z_0 - r_0/(2*(200-1)))
t_crit = norm.ppf(1-alpha/2)

print("T: ", t_eval)
print("T крит.: ", t_crit)

T:  0.7963323438353612
T крит.:  1.959963984540054
