In [1]:
import numpy as np
import math

n = 50
lambda_par = 0.5

In [15]:
# Генерация распределений длин ребер показательно
def generate_selection():
  select_data = []
  for _ in range(0, n):
    row = [-1/lambda_par * math.log(1 - x) for x in np.random.uniform(size=5)]
    select_data.append(row)
  return np.array(select_data)

In [26]:
# случайный вектор средних
vect = np.array([float(item) for item in input("Введите случайный вектор (N = 5)").split()][:5])

# матрица ковариаций
cov_matrix = np.array(
 [[1., 0, 0, 0, 0],
 [0, 1, 0, 0, 0,],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]
)

def generate_selection():
  # Генерация распределений длин ребер через вектор средних и матрицу ковариаций
  a = np.linalg.cholesky(cov_matrix)
  selection_data = []
  for _ in range(0, n):
    observ = np.matmul(a, np.random.normal(0, 1, 5).T)
    observ = np.add(observ, vect)
    selection_data.append(observ)

  return np.array(selection_data)

In [27]:
selection = generate_selection()
print(selection[:3])

[[ 0.49052356 -0.05373083  3.15028522  3.6660441   5.01555593]
 [-0.23748194  2.06192079  4.40460144  6.33554723  5.64598428]
 [ 0.18038859  2.6724585   3.37711787  4.50884148  6.30720935]]


In [28]:
means = [np.mean(row) for row in selection.T]
print(means)

routes = []

lambda_dict = {
  "x1->x4": lambda row: row[0] + row[3],
  "x2->x5": lambda row: row[1] + row[4],
  "x1->x3->x5": lambda row: row[0] + row[2] + row[4],
  "x2->x3->x4": lambda row: row[1] + row[2] + row[3]
}

routes.append(("x1->x4", lambda_dict["x1->x4"](means)))
routes.append(("x2->x5", lambda_dict["x2->x5"](means)))
routes.append(("x1->x3->x5", lambda_dict["x1->x3->x5"](means)))
routes.append(("x2->x3->x4", lambda_dict["x2->x3->x4"](means)))

min_route = min(routes, key=lambda t: t[1])
print(min_route)

[1.0527896677377424, 1.9389937766825769, 3.022946909355828, 4.1252663154538824, 5.144762669716131]
('x1->x4', 5.178055983191625)


In [29]:
# Высчитываем значение U
u = np.average(means)
print("U =", u)

U = 3.056951867789232


In [30]:
count = 0
for row in selection:
  distance = lambda_dict[min_route[0]](row)
  if distance > u:
    count += 1

prob = count / n
print(prob)

0.98
